version: '3'

services:
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app  

  app:
    build: docker/app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql

  websocket:
    build: ./docker/server
    ports:
      - "9502:9502"
    volumes:
      - .:/var/www
    environment:
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ANY_FILES: 0
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: messenger
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
